version: '3.8'

services:

############# Generals #############

  elasticsearch:
    image: elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    networks:
      - backend
    env_file:
      - src/.env

  redis:
    image: redis:6.2.6
    container_name: redis
    command:
      - redis-server
    networks:
      - backend
    env_file:
      - src/.env

############ async_api #############

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    networks:
      - backend
    depends_on:
      - redis
    env_file:
      - src/.env


############# Nginx #############
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80 # async_api
    depends_on:
      - api
    networks:
      - backend


networks:
  backend:
    driver: bridge