version: '3.8'

services:

############# Generals #############
  redis:
    image: redis:6.2.6
    container_name: redis
    command:
      - redis-server
    networks:
      - backend
    env_file:
      - .env

############# Nginx #############
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 5555:80 # admin_panel
      - 80:80 # async_api
    depends_on:
      - api
    networks:
      - backend

############# asymc_api #############
  api:
    build:
      context: ./async_api/src
      dockerfile: Dockerfile
    container_name: api
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  static_volume:
  media_volume:

networks:
  backend:
    driver: bridge